-- 21 de Diciembre de 2000
CREATE SEQUENCE ID_IBI_FINCA_FURB INCREMENT BY 1 START WITH 1;
CREATE PUBLIC SYNONYM ID_IBI_FINCA_FURB FOR GIALNET.ID_IBI_FINCA_FURB;
CREAR LAS TABLAS IBI_FINCA_FURB,IBI_SUELO_FURB,IBI_CONSTRUCTIVA_FURB,
IBI_CARGO_FURB,IBI_CONSTRUCCION_FURB,IBI_REPARTO_CARGOS_FURB,IBI_REPARTO_CONSTRUCCION_FURB;
CREATE PUBLIC SYNONYM IBI_FINCA_FURB FOR GIALNET.IBI_FINCA_FURB;
CREATE PUBLIC SYNONYM IBI_SUELO_FURB FOR GIALNET.IBI_SUELO_FURB;
CREATE PUBLIC SYNONYM IBI_CONSTRUCTIVA_FURB FOR GIALNET.IBI_CONSTRUCTIVA_FURB;
CREATE PUBLIC SYNONYM IBI_CARGO_FURB FOR GIALNET.IBI_CARGO_FURB;
CREATE PUBLIC SYNONYM IBI_CONSTRUCCION_FURB FOR GIALNET.IBI_CONSTRUCCION_FURB;
CREATE PUBLIC SYNONYM IBI_REPARTO_CARGOS_FURB FOR GIALNET.IBI_REPARTO_CARGOS_FURB;
CREATE PUBLIC SYNONYM IBI_REPARTO_CONSTRUCCION_FURB FOR GIALNET.IBI_REPARTO_CONSTRUCCION_FURB;
CREATE OR REPLACE TRIGGER ADD_IBI_FINCA_FURB en el archivo 23 TRIGGERS_FINURB-98.SQL;
CREATE OR REPLACE PROCEDURE CARGAR_VARPAD en el archivo 20_VARPAD.SQL;
CREATE SEQUENCE ID_IBI_CARGO_FURB INCREMENT BY 1 START WITH 1;
CREATE PUBLIC SYNONYM ID_IBI_CARGO_FURB FOR GIALNET.ID_IBI_CARGO_FURB;
CREATE OR REPLACE TRIGGER ADD_IBI_CARGO_FURB en el archivo 23 TRIGGERS_FINURB-98.SQL;
CREATE OR REPLACE PROCEDURE ALTA_VARPAD en el archivo 20_VARPAD.SQL
CREATE PUBLIC SYNONYM ALTA_VARPAD FOR GIALNET.ALTA_VARPAD;
CREATE OR REPLACE PROCEDURE MODIFICACION_VARPAD en el archivo 20_VARPAD.SQL;
CREATE PUBLIC SYNONYM MODIFICACION_VARPAD FOR GIALNET.MODIFICACION_VARPAD;
CREATE OR REPLACE PROCEDURE BAJA_VARPAD en el archivo 20_VARPAD.SQL;
CREATE PUBLIC SYNONYM BAJA_VARPAD FOR GIALNET.BAJA_VARPAD;

-- 8 DE ENERO DE 2000
ALTER TABLE VARPAD ADD USUARIO CHAR(30) DEFAULT USER NOT NULL;
ALTER TABLE VARPAD ADD QUIEN_MODIFICA CHAR(1) DEFAULT 'G' NOT NULL;
CREATE OR REPLACE PROCEDURE INSERTA_VARPAD en el archivo 20_VARPAD.SQL;
CREATE OR REPLACE PROCEDURE MODI_VARPAD_FIN98 en el archivo 23_IBI_FINURB-98.SQL;
CREATE PUBLIC SYNONYM MODI_VARPAD_FIN98 FOR GIALNET.MODI_VARPAD_FIN98;




--23 de febrero de 2001
CREATE OR REPLACE PROCEDURE INSERTA_REGISTRO_IAE;
CREATE OR REPLACE PROCEDURE COMPRUEBA_BAJA;
CREATE OR REPLACE PROCEDURE GENERA_PADRON_IAE;
CREATE OR REPLACE PROCEDURE IAE_GENERA_LIQUIDACIONES;
CREATE OR REPLACE FUNCTION QUARTER en 02_varios.sql;

--27 de Febrero de 2001
CREATE TABLE OFICINAS en el archivo GT.SQL;
CREATE PUBLIC SYNONYM OFICINAS FOR GIALNET.OFICINAS;

--1 de Marzo de 2001
CREATE OR REPLACE PROCEDURE ADD_OFICINAS en el archivo 02_VARIOS.SQL;
CREATE PUBLIC SYNONYM ADD_OFICINAS FOR GIALNET.ADD_OFICINAS;

--6 de Marzo de 2001
CREATE OR REPLACE PROCEDURE INSERTA_IBI_FINCA_FURB en el archivo 23_IBI_FINURB-98.SQL;
CREATE PUBLIC SYNONYM INSERTA_IBI_FINCA_FURB FOR GIALNET.INSERTA_IBI_FINCA_FURB;
CREATE OR REPLACE TRIGGER T_INS_IBI_FINCA_FURB en el archivo 23_IBI_FINURB-98.SQL;

--7 de Marzo de 2001
CREATE OR REPLACE PROCEDURE EXAC_PASE_RECA en 13_Exacciones.sql;
CREATE INDEX IN_TRIBUTOSCPROGRAMA ON TRIBUTOSCONTRI (ID_CONCEPTO,PROGRAMA) TABLESPACE INDICES;
CREATE OR REPLACE TRIGGER EXACCIONES_MOD_TR EN 13_TRIGGER_EXACCIONES.SQL;

-- 20 de Marzo de 2001

CREATE TABLE ENTREGA_DENUNCIA (
	CODIGO	INTEGER NOT NULL,
	MUNICIPIO	CHAR(3) DEFAULT '000' NOT NULL,
	MOTIVO	VARCHAR(70),
	PRIMARY KEY (CODIGO)
) TABLESPACE TABLASCONFIG;

CREATE PUBLIC SYNONYM ENTREGA_DENUNCIA FOR GIALNET.ENTREGA_DENUNCIA;
CREATE SEQUENCE GENENTREGA INCREMENT BY 1 START WITH 1;
CREATE OR REPLACE TRIGGER SET_ENTREGA_DENUNCIA
BEFORE INSERT ON ENTREGA_DENUNCIA
FOR EACH ROW

BEGIN
   SELECT GENENTREGA.NEXTVAL INTO :NEW.CODIGO FROM DUAL; 
END;
/

ALTER TABLE MULTAS ADD COD_ENTREGA INTEGER NOT NULL;
ALTER TABLE MULTAS ADD CONSTRAINT MULTASENTREGA
	FOREIGN KEY (COD_ENTREGA)
	REFERENCES ENTREGA_DENUNCIA (CODIGO);

CREATE OR REPLACE PROCEDURE InsertaBoletin en el archivo 12_MULTAS.SQL;
CREATE OR REPLACE PROCEDURE ModificaBoletin en el archivo 12_MULTAS.SQL;

--31 Marzo 2001

CREATE INDEX IBINIF ON IBI (NIF) TABLESPACE INDICES;
CREATE INDEX IBINOMBRE ON IBI (NOMBRE) TABLESPACE INDICES;
CREATE INDEX IBIMUNIYEAR ON IBI (MUNICIPIO,YEAR) TABLESPACE INDICES;

CREATE INDEX RECI_IBIABONADO ON RECIBOS_IBI (ABONADO) TABLESPACE INDICES;
CREATE INDEX RECI_IBINOMBRE ON RECIBOS_IBI (NOMBRE) TABLESPACE INDICES;

-- 4 de Abril de 2001
ALTER TABLE USUARIOSGT ADD CONF_AYTO INTEGER DEFAULT 0;
--habría que eliminar los campos CONF_AYTO_VADOS,CONF_AYTO_MULTAS,
					   CONF_AYTO_AGUAS,CONF_AYTO_EXAC

DROP PROCEDURE READ_COMO_CREO_EXAC;
DROP PUBLIC SYNONYM READ_COMO_CREO_EXAC;
DROP PROCEDURE PUT_COMO_CREO_EXAC;
DROP PUBLIC SYNONYM PUT_COMO_CREO_EXAC;

--10 de Abril de 2001
CREATE OR REPLACE PROCEDURE ANULAR_CARGO EN 03_LIQUIDACIONES.SQL;

/************************* actualizado hasta aqui en malaga ********************************/
-- 8 de Mayo de 2001

ALTER TABLE PUNTEO MODIFY PROVINCIA VARCHAR(35) DEFAULT'';
ALTER TABLE PUNTEO MODIFY PAIS VARCHAR(35) DEFAULT'';

CREATE OR REPLACE PROCEDURE VEHI_PASE_RECA en el archivo 06_VEHICULOS.SQL;
CREATE OR REPLACE PROCEDURE LIQUI_PASE_RECA en el archivo 03_LIQUIDACIONES.SQL;
CREATE OR REPLACE PROCEDURE AGUA_PASE_RECA en el archivo 17_AGUAS_EMISION_DE_RECIBOS.SQL;
CREATE OR REPLACE PROCEDURE IBI_PASE_RECA en el archivo 04_IBI.SQL;
CREATE OR REPLACE PROCEDURE RUS_PASE_RECA en el archivo 08_RUSTICA.SQL;
CREATE OR REPLACE PROCEDURE EXAC_PASE_RECA en el archivo 13_EXACCIONES.SQL;
CREATE OR REPLACE PROCEDURE IAE_PASE_RECA en el archivo 05_IAE.SQL;




--15 de mayo de 2001
CREATE OR REPLACE PROCEDURE Proc_Caixa_Vehi en 06_vehiculos.sql;
CREATE OR REPLACE PROCEDURE Proc_Caixa_IBI en 04_ibi.sql;
CREATE OR REPLACE PROCEDURE Proc_Caixa_IAE en 05_iae.sql;
CREATE OR REPLACE PROCEDURE Proc_Caixa_rustica en 08_rustica.sql;
CREATE OR REPLACE PROCEDURE Proc_Caixa_EXAC en 13_exacciones.sql;
CREATE OR REPLACE PROCEDURE Proc_Caixa_Agua en 17_AGUAS_EMISION_DE_RECIBOS.SQL;


--comprobar si existen estos indices 
CREATE INDEX RECI_IBIABONADO ON RECIBOS_IBI (ABONADO) TABLESPACE INDICES;
CREATE INDEX RECI_IBINOMBRE ON RECIBOS_IBI (NOMBRE) TABLESPACE INDICES;


--6 de junio de 2001
drop TABLE PASAR_DBASE;
create TABLE PASAR_DBASE;
CREATE OR REPLACE PROCEDURE PASA_EXPEDIENTE_DBASE en 12_MULTAS.SQL;
CREATE OR REPLACE PROCEDURE PASA_A_DBASE en 12_MULTAS.SQL;

-- 13 de Junio de 2001
DROP TRIGGER SET_AGENTES;
DROP SEQUENCE GENAGENTE;

-- 16 de Junio de 2001
DROP TABLE IMP_RECIBOS_RUS;
CREATE TABLE IMP_RECIBOS_RUS en gt.sql;
CREATE OR REPLACE PROCEDURE Imprime_Recibos_Rus en el archivo 08_RUSTICA.SQL;
CREATE OR REPLACE PROCEDURE Imprime_Recibos_Rus_F en el archivo 08_RUSTICA.SQL;
CREATE PUBLIC SYNONYM Imprime_Recibos_Rus_F FOR GIALNET.Imprime_Recibos_Rus_F;

-- 19 de Junio de 2001
CREATE OR REPLACE PROCEDURE INSERTA_RECIBO_FICTICIO en el archivo 02_VARIOS.SQL;

-- 25 de Junio de 2001
CREATE OR REPLACE PROCEDURE ANULAR_LIQUI en el archivo 03_LIQUIDACIONES.SQL;

-- 26 de Junio DE 2001
CREATE OR REPLACE PROCEDURE PASA_EXPEDIENTE_DBASE en el archivo 12_MULTAS.SQL;

-- 28 de Junio de 2001
CREATE OR REPLACE PROCEDURE Imprime_Recibos_Rus_F en el archivo 08_RUSTICA.SQL;

--29 DE JUNIO DE 2001
CREATE OR REPLACE PROCEDURE InsertaModiContribuyente en el archivo 02_varios.sql;
lanzar todo el fichero de 04_ibi.sql;
CREATE OR REPLACE PROCEDURE INSERTA_REGISTRO_RUSTICA en 08_rustica.sql;

-- 2 de Julio de 2001
CREATE OR REPLACE PROCEDURE GENERA_PADRON_IBI en el archivo 04_IBI.SQL;
CREATE OR REPLACE PROCEDURE InsertaModiContribuyente en el archivo 02_varios.sql;
CREATE OR REPLACE PROCEDURE Imprime_Recibos_Ibi en el archivo 04_IBI.SQL;

CREATE OR REPLACE PROCEDURE Imprime_Recibos_Rus en 08_rustica.sql;
CREATE OR REPLACE PROCEDURE DAME_DATOS_PARCELAS en 08_rustica.sql;
CREATE PUBLIC SYNONYM DAME_DATOS_PARCELAS FOR GIALNET.DAME_DATOS_PARCELAS;
CREATE OR REPLACE PROCEDURE Imprime_Recibos_Rus_F en 08_rustica.sql;

-- 3 de julio de 2001

ALTER TABLE RECIBOS_EXAC ADD 	DOMICILIO		VARCHAR(50);
ALTER TABLE RECIBOS_IAE  ADD 	DOMICILIO		VARCHAR(50);
ALTER TABLE RECIBOS_AGUA ADD 	DOMICILIO		VARCHAR(50);

--4 DE JULIO DE 2001
CREATE OR REPLACE PROCEDURE F_DC60 EN 02_VARIOS.SQL;
CREATE OR REPLACE PROCEDURE CALCULA_DC_MODALIDAD2_60 EN 02_VARIOS.SQL;
CREATE PUBLIC SYNONYM CALCULA_DC_MODALIDAD2_60 FOR GIALNET.CALCULA_DC_MODALIDAD2_60;

alter table recibos_ibi add DISCRI_PERIODO CHAR(1) DEFAULT '1';
alter table recibos_ibi add DIGITO_YEAR CHAR(1);
alter table recibos_ibi add F_JULIANA CHAR(3);
alter table recibos_ibi add DIGITO_C60_MODALIDAD2 CHAR(2);

alter table recibos_vehi add DISCRI_PERIODO CHAR(1) DEFAULT '1';
alter table recibos_vehi add DIGITO_YEAR CHAR(1);
alter table recibos_vehi add F_JULIANA CHAR(3);
alter table recibos_vehi add DIGITO_C60_MODALIDAD2 CHAR(2);

alter table recibos_agua add DISCRI_PERIODO CHAR(1) DEFAULT '1';
alter table recibos_agua add DIGITO_YEAR CHAR(1);
alter table recibos_agua add F_JULIANA CHAR(3);
alter table recibos_agua add DIGITO_C60_MODALIDAD2 CHAR(2);

alter table recibos_rustica add DISCRI_PERIODO CHAR(1) DEFAULT '1';
alter table recibos_rustica add DIGITO_YEAR CHAR(1);
alter table recibos_rustica add F_JULIANA CHAR(3);
alter table recibos_rustica add DIGITO_C60_MODALIDAD2 CHAR(2);

alter table recibos_exac add DISCRI_PERIODO CHAR(1) DEFAULT '1';
alter table recibos_exac add DIGITO_YEAR CHAR(1);
alter table recibos_exac add F_JULIANA CHAR(3);
alter table recibos_exac add DIGITO_C60_MODALIDAD2 CHAR(2);

alter table recibos_iae add DISCRI_PERIODO CHAR(1) DEFAULT '1';
alter table recibos_iae add DIGITO_YEAR CHAR(1);
alter table recibos_iae add F_JULIANA CHAR(3);
alter table recibos_iae add DIGITO_C60_MODALIDAD2 CHAR(2);

alter table IMP_RECIBOS_IBI add DISCRI_PERIODO CHAR(1) DEFAULT '1';
alter table IMP_RECIBOS_IBI add DIGITO_YEAR CHAR(1);
alter table IMP_RECIBOS_IBI add F_JULIANA CHAR(3);
alter table IMP_RECIBOS_IBI add DIGITO_C60_MODALIDAD2 CHAR(2);
alter table IMP_RECIBOS_IBI add COD_BARRAS_MOD1	char(38);
alter table IMP_RECIBOS_IBI add COD_BARRAS_MOD2	char(42);

alter table IMP_RECIBOS_vehi add DISCRI_PERIODO CHAR(1) DEFAULT '1';
alter table IMP_RECIBOS_vehi add DIGITO_YEAR CHAR(1);
alter table IMP_RECIBOS_vehi add F_JULIANA CHAR(3);
alter table IMP_RECIBOS_vehi add DIGITO_C60_MODALIDAD2 CHAR(2);
alter table IMP_RECIBOS_vehi add COD_BARRAS_MOD1	char(38);
alter table IMP_RECIBOS_vehi add COD_BARRAS_MOD2	char(42);

alter table IMP_RECIBOS_agua add DISCRI_PERIODO CHAR(1) DEFAULT '1';
alter table IMP_RECIBOS_agua add DIGITO_YEAR CHAR(1);
alter table IMP_RECIBOS_agua add F_JULIANA CHAR(3);
alter table IMP_RECIBOS_agua add DIGITO_C60_MODALIDAD2 CHAR(2);
alter table IMP_RECIBOS_agua add COD_BARRAS_MOD1	char(38);
alter table IMP_RECIBOS_agua add COD_BARRAS_MOD2	char(42);

alter table IMP_RECIBOS_rus add DISCRI_PERIODO CHAR(1) DEFAULT '1';
alter table IMP_RECIBOS_rus add DIGITO_YEAR CHAR(1);
alter table IMP_RECIBOS_rus add F_JULIANA CHAR(3);
alter table IMP_RECIBOS_rus add DIGITO_C60_MODALIDAD2 CHAR(2);
alter table IMP_RECIBOS_rus add COD_BARRAS_MOD1	char(38);
alter table IMP_RECIBOS_rus add COD_BARRAS_MOD2	char(42);

alter table IMP_RECIBOS_exac add DISCRI_PERIODO CHAR(1) DEFAULT '1';
alter table IMP_RECIBOS_exac add DIGITO_YEAR CHAR(1);
alter table IMP_RECIBOS_exac add F_JULIANA CHAR(3);
alter table IMP_RECIBOS_exac add DIGITO_C60_MODALIDAD2 CHAR(2);
alter table IMP_RECIBOS_exac add COD_BARRAS_MOD1	char(38);
alter table IMP_RECIBOS_exac add COD_BARRAS_MOD2	char(42);

alter table IMP_RECIBOS_IAE add DISCRI_PERIODO CHAR(1) DEFAULT '1';
alter table IMP_RECIBOS_IAE add DIGITO_YEAR CHAR(1);
alter table IMP_RECIBOS_IAE add F_JULIANA CHAR(3);
alter table IMP_RECIBOS_IAE add DIGITO_C60_MODALIDAD2 CHAR(2);
alter table IMP_RECIBOS_IAE add COD_BARRAS_MOD1	char(38);
alter table IMP_RECIBOS_IAE add COD_BARRAS_MOD2	char(42);

CREATE OR REPLACE PROCEDURE GENERA_PADRON_IBI en 04_IBI.SQL;
CREATE OR REPLACE PROCEDURE Imprime_Recibos_Ibi en 04_IBI.SQL;
CREATE OR REPLACE PROCEDURE INSERTA_RECIBO_FICTICIO en 02_varios.sql;

CREATE OR REPLACE PROCEDURE GENERA_PADRON_VEHI en 06_VEHICULOS.SQL;
CREATE OR REPLACE PROCEDURE IMPRIME_RECIBOS_VEHI en 06_VEHICULOS.SQL;

CREATE OR REPLACE PROCEDURE GEN_RECIBOS_AGUA en 17_AGUAS_EMISION_DE_RECIBOS.SQL;
CREATE OR REPLACE PROCEDURE Imprime_Recibos_Agua en 17_AGUAS_EMISION_DE_RECIBOS.SQL;

CREATE OR REPLACE PROCEDURE GENERA_PADRON_RUS en 08_RUSTICA.SQL;
CREATE OR REPLACE PROCEDURE GENPAD_RUS81 en 08_RUSTICA.SQL;
CREATE OR REPLACE PROCEDURE Imprime_Recibos_Rus en 08_RUSTICA.SQL;
CREATE OR REPLACE PROCEDURE Imprime_Recibos_Rus_F en 08_RUSTICA.SQL;

CREATE OR REPLACE PROCEDURE GENERA_PADRON_EXACCIONES en 13_EXACCIONES.SQL;
CREATE OR REPLACE PROCEDURE Imprime_Recibos_Exac en 13_EXACCIONES.SQL;

CREATE OR REPLACE PROCEDURE GENERA_PADRON_IAE en 05_IAE.SQL;
CREATE OR REPLACE PROCEDURE IMPRIME_RECIBOS_IAE en 05_IAE.SQL;

-- 6 de julio de 2001
alter table liquidaciones add DISCRI_PERIODO CHAR(1) DEFAULT '1';
alter table liquidaciones add DIGITO_YEAR CHAR(1);
alter table liquidaciones add F_JULIANA CHAR(3);
alter table liquidaciones add DIGITO_C60_MODALIDAD2 CHAR(2);
alter table liquidaciones add EMISOR 	CHAR(6);
alter table liquidaciones add TRIBUTO	CHAR(3);
alter table liquidaciones add EJER_C60 	CHAR(2);
alter table liquidaciones add REFERENCIA	CHAR(10);
alter table liquidaciones add IMP_CADENA	CHAR(12) DEFAULT '0';

CREATE OR REPLACE PROCEDURE ADD_LIQUI en 03_liquidaciones.sql;
CREATE OR REPLACE VIEW TABLA_LIQUIDACIONES;

-- 7 de julio de 2001
CREATE OR REPLACE PROCEDURE INSERTA_PLUSVALIA en 09_plusvalias.sql;
CREATE OR REPLACE PROCEDURE MODIFICA_PLUSVALIA en 09_plusvalias.sql;

-- 10 de julio de 2001
alter table tabla_plusva add EMISOR CHAR(6);
alter table tabla_plusva add TRIBUTO CHAR(3);
alter table tabla_plusva add EJER_C60 CHAR(2);
alter table tabla_plusva add REFERENCIA CHAR(10);
alter table tabla_plusva add IMP_CADENA CHAR(12) DEFAULT '0';
alter table tabla_plusva add DISCRI_PERIODO CHAR(1) DEFAULT '1';
alter table tabla_plusva add DIGITO_YEAR CHAR(1);
alter table tabla_plusva add F_JULIANA CHAR(3);
alter table tabla_plusva add DIGITO_C60_MODALIDAD2 CHAR(2);
alter table tabla_plusva add F_FIN_PE_VOL	 DATE;
alter table tabla_plusva add CODIGO_BARRAS char(42);
CREATE OR REPLACE PROCEDURE PROC_TABLA_PLUSVA en 09_plusvalias.sql;
CREATE OR REPLACE PROCEDURE RUS_MODIFICA en 08_rustica.sql;

-- 23 de Julio de 2001
CREATE OR REPLACE PROCEDURE Proc_Caixa_Rustica en el archivo 08_RUSTICA.SQL;

/************************* actualizado hasta aqui en albuñol ********************************/

-- 24 DE JULIO DE 2001

-- 26 de Julio de 2001
ALTER TABLE USUARIOSGT ADD ID INTEGER;
ALTER TABLE USUARIOSGT ADD CONSTRAINT USUARIOGTID UNIQUE (ID);
create or replace procedure RellenaID as
   i integer;
   cursor c1 is select * from usuariosgt;
begin
   i:=0;
   for v_cursor in c1
   loop
      i:=i+1;
      update usuariosgt set id=i where usuario=v_cursor.USUARIO;
   end loop;
end;
/
execute RellenaID;
drop procedure RellenaID;

ALTER TABLE USUARIOSGT MODIFY ID INTEGER NOT NULL;
CREATE SEQUENCE GEN_ID_USUARIOSGT INCREMENT BY 1 START WITH ?;


-- 30 de Julio de 2001

CREATE OR REPLACE VIEW TABLA_LIQUIDACIONES en el archivo 01_GT.SQL;
CREATE PUBLIC SYNONYM DatosOtroNIF FOR GIALNET.DatosOtroNIF;

CREATE OR REPLACE VIEW VWLIQUI;
CREATE PUBLIC SYNONYM VWLIQUI FOR GIALNET.VWLIQUI;

CREATE OR REPLACE VIEW vwVehiculos EN 01_GT.SQL;
CREATE PUBLIC SYNONYM VWVEHICULOS FOR GIALNET.VWVEHICULOS;

CREATE OR REPLACE VIEW vwAGUA EN 01_GT.SQL;
CREATE PUBLIC SYNONYM vwAGUA FOR GIALNET.vwAGUA;

CREATE OR REPLACE VIEW VWPLUSVALIAS EN 01_GT.SQL;
CREATE PUBLIC SYNONYM VWPLUSVALIAS FOR GIALNET.VWPLUSVALIAS;

CREATE OR REPLACE VIEW VWIBI EN 01_GT.SQL;
CREATE PUBLIC SYNONYM VWIBI FOR GIALNET.VWIBI;

CREATE OR REPLACE VIEW VWEXAC EN 01_GT.SQL;
CREATE PUBLIC SYNONYM VWEXAC FOR GIALNET.VWEXAC;

CREATE OR REPLACE VIEW vwRus80 EN 01_GT.SQL;
CREATE PUBLIC SYNONYM vwRus80 FOR GIALNET.vwRus80;

CREATE OR REPLACE VIEW VWIAE EN 01_GT.SQL;
CREATE PUBLIC SYNONYM VWIAE FOR GIALNET.VWIAE;

CREATE INDEX IN_RUS81_ABONADO ON RUS81(ABONADO) TABLESPACE INDICES;


DROP PROCEDURE INCORPORAR_PADRON;
DROP PROCEDURE DEL_CARGA_CONTRI_IAE;
DROP PROCEDURE CORREGIR_CONTRI_IAE;
DROP PROCEDURE MODI_CONTRI_CARGA_IAE;
DROP PROCEDURE CARGAR_IAE;

DROP PUBLIC SYNONYM INCORPORAR_PADRON;
DROP PUBLIC SYNONYM DEL_CARGA_CONTRI_IAE;
DROP PUBLIC SYNONYM CORREGIR_CONTRI_IAE;
DROP PUBLIC SYNONYM MODI_CONTRI_CARGA_IAE;
DROP PUBLIC SYNONYM CARGAR_IAE;

DROP TABLE CARGA_IAE;
DROP TABLE CARGA_CONTRI;
DROP PUBLIC SYNONYM CARGA_IAE;
DROP PUBLIC SYNONYM CARGA_CONTRI;

-- 1 DE AGOSTO DE 2001

CREATE OR REPLACE VIEW VWDOMICILIACIONESCONTRI EN 01_GT.SQL;
CREATE PUBLIC SYNONYM VWDOMICILIACIONESCONTRI FOR GIALNET.VWDOMICILIACIONESCONTRI;

CREATE OR REPLACE VIEW VWTRIBUTOSCONTRI EN 01_GT.SQL;
CREATE PUBLIC SYNONYM VWTRIBUTOSCONTRI FOR GIALNET.VWTRIBUTOSCONTRI;

-- 2 DE AGOSTO DE 2001
UPDATE PROGRAMAS SET CONSULTA_REC='SELECT * FROM TABLA_REQUE_PLUSVA WHERE ID=:xID'
WHERE PROGRAMA='PLUSVALIA';
ALTER TABLE TABLA_REQUE_PLUSVA ADD ID INTEGER;

drop table sinonimos;
drop PROCEDURE ADD_SINONIMO;
drop PROCEDURE BORRAR_CONTRIB_SINONIMO;

CREATE TABLE COTITULARES;
CREATE PUBLIC SYNONYM COTITULARES FOR GIALNET.COTITULARES;
CREATE OR REPLACE VIEW VWCOTITULARES;
CREATE PUBLIC SYNONYM VWCOTITULARES FOR GIALNET.VWCOTITULARES;
CREATE SEQUENCE GENCOTITULARES INCREMENT BY 1 START WITH 1;
CREATE PUBLIC SYNONYM GENCOTITULARES FOR GIALNET.GENCOTITULARES;
CREATE PUBLIC SYNONYM AddCOTITULARES FOR GIALNET.AddCOTITULARES;
CREATE PUBLIC SYNONYM DelCOTITULARES FOR GIALNET.DelCOTITULARES;


CREATE TABLE COTITULARES_RECIBO;
CREATE OR REPLACE VIEW VWCOTITULARESREC;
CREATE PUBLIC SYNONYM COTITULARES_RECIBO FOR GIALNET.COTITULARES_RECIBO;
CREATE PUBLIC SYNONYM VWCOTITULARESREC FOR GIALNET.VWCOTITULARESREC;
CREATE SEQUENCE GEN_REC_COTITULARES INCREMENT BY 1 START WITH 1;
CREATE PUBLIC SYNONYM GEN_REC_COTITULARES FOR GIALNET.GEN_REC_COTITULARES;

ALTER TABLE VEHICULOS ADD COTITULARES CHAR(1) DEFAULT 'N' check (COTITULARES in ('S','N'));
ALTER TABLE VEHICULOS ADD IDDOMIALTER	 INTEGER;
ALTER TABLE VEHICULOS ADD REPRESENTANTE     CHAR(10);

ALTER TABLE VEHICULOS ADD CONSTRAINT VEHIDOMIALTER
       FOREIGN KEY (IDDOMIALTER)
       REFERENCES DOMICILIOS_ALTERNATIVOS(ID);

alter table recibos_vehi drop CONSTRAINT RECIVEHINIF;
alter table recibos_exac drop CONSTRAINT RECEAXCNIF;
alter table recibos_exac drop CONSTRAINT RECEXACFACTURAR;
alter table recibos_agua drop CONSTRAINT RECAGUANIF;
alter table recibos_iae drop CONSTRAINT RECIAETITULAR;
ALTER TABLE cod_provincias DROP CONSTRAINT CODIGO_PROVINCIA;

CREATE TABLE CODIGOS_POSTALES(
	ID 			INTEGER NOT NULL,
	CODPROV		CHAR(2) NOT NULL,
	POBLACION		CHAR(50),
	CODIGO_POSTAL	CHAR(5) NOT NULL,
	PRIMARY KEY(ID),

	CONSTRAINT CODPOSTALES
	FOREIGN KEY (CODPROV)
	REFERENCES COD_PROVINCIAS(CODPROV)
);
CREATE INDEX IN_CODPOSTALES ON CODIGOS_POSTALES (CODIGO_POSTAL) TABLESPACE INDICES;
CREATE INDEX IN_CODPOBLACION ON CODIGOS_POSTALES (POBLACION) TABLESPACE INDICES;

CREATE PUBLIC SYNONYM CODIGOS_POSTALES FOR GIALNET.CODIGOS_POSTALES;
CREATE SEQUENCE GEN_CODIGOS_POSTALES INCREMENT BY 1 START WITH 1;
CREATE PUBLIC SYNONYM GEN_CODIGOS_POSTALES FOR GIALNET.GEN_CODIGOS_POSTALES;

--3 de Agosto de 2001
CREATE PUBLIC SYNONYM NEXT_ITEM FOR GIALNET.NEXT_ITEM;
CREATE PUBLIC SYNONYM GENERA_RECIBOS_AGUA FOR GIALNET.GENERA_RECIBOS_AGUA;

-- 6 de Agosto de 2001
CREATE TABLE TMP_AYTOS en el archivo 01_GT.SQL;
CREATE PUBLIC SYNONYM TMP_AYTOS FOR GIALNET.TMP_AYTOS;

-- 7 de Agosto de 2001
alter table desglose_aguas drop CONSTRAINT DESGLOAGUAPERIODO;
alter table desglose_aguas add CONSTRAINT DESGLOAGUAPERIODO
	FOREIGN KEY (MUNICIPIO,YEAR, PERIODO, ABONADO) 
	REFERENCES RECIBOS_AGUA(MUNICIPIO,YEAR, PERIODO, ABONADO);

CREATE PUBLIC SYNONYM GEN_PADRON_VEHI FOR GIALNET.GEN_PADRON_VEHI;

ALTER TABLE DATOS_ORDENANTE DROP PRIMARY KEY;
ALTER TABLE DATOS_ORDENANTE ADD PRIMARY KEY(NIF);

CREATE PUBLIC SYNONYM GENERA_RECIBOS_IBI FOR GIALNET.GENERA_RECIBOS_IBI;

-- 8 de agosto de 2001
alter table vehiculos_trafico add ID INTEGER;
CREATE SEQUENCE GEN_ID_VEHITRAFICO INCREMENT BY 1 START WITH 7;

create or replace procedure RellenaIDTrafico as
   i integer;
   cursor c1 is select * from vehiculos_trafico;
begin
   i:=0;
   for v_cursor in c1
   loop
      i:=i+1;
      update vehiculos_trafico set id=i where vehiculo=v_cursor.Vehiculo;
   end loop;
end;
/
execute RellenaIDTrafico;
drop procedure RellenaIDTrafico;

CREATE PUBLIC SYNONYM GENERA_RECIBOS_RUS FOR GIALNET.GENERA_RECIBOS_RUS;
CREATE PUBLIC SYNONYM GENERA_RECIBOS_EXACCIONES FOR GIALNET.GENERA_RECIBOS_EXACCIONES;
CREATE PUBLIC SYNONYM GENERA_RECIBOS_IAE FOR GIALNET.GENERA_RECIBOS_IAE;

-- 13 de Agosto de 2001
************************************************************************************
--HAY QUE LANZAR EL FICHERO CORRESPONDIENTE A LOS ARREGLOS DEL EPIGRAFE.SQL;
************************************************************************************

-- 14 de Agosto de 2001
CREATE PUBLIC SYNONYM EstaDomiciliado FOR GIALNET.EstaDomiciliado;

-- 16 de Agosto de 2001
CREATE OR REPLACE VIEW VWPLUSVALIAS en 01_GT.SQL;

-- 17 de Agosto de 2001
CREATE OR REPLACE VIEW VWEXAC en el archivo 01_GT.SQL;

CREATE PUBLIC SYNONYM GETMATRICULA FOR GIALNET.GETMATRICULA;
CREATE OR REPLACE VIEW vwVehiculos;

-- 20 DE AGOSTO DE 2001
alter table recibos_vehi add  POBLACION       VARCHAR2(35);
alter table recibos_vehi add  PROVINCIA       VARCHAR2(35);
alter table recibos_vehi add  CODIGO_POSTAL   CHAR(5);

drop table IMP_RECIBOS_VEHI;
CREATE TABLE IMP_RECIBOS_VEHI;

CREATE PUBLIC SYNONYM GetDomicilioFiscal FOR GIALNET.GetDomicilioFiscal;
CREATE PUBLIC SYNONYM WriteTempVehi FOR GIALNET.WriteTempVehi;


-- 21 de agosto de 2001
ALTER TABLE EXACCIONES ADD COTITULARES CHAR(1) DEFAULT 'N' check (COTITULARES in ('S','N'));
ALTER TABLE EXACCIONES ADD IDDOMIALTER	 INTEGER;
ALTER TABLE EXACCIONES ADD REPRESENTANTE     CHAR(10);
ALTER TABLE EXACCIONES ADD CONSTRAINT EXACDOMIALTER
       FOREIGN KEY (IDDOMIALTER)
       REFERENCES DOMICILIOS_ALTERNATIVOS(ID);

CREATE OR REPLACE VIEW VWEXAC;

alter table RECIBOS_EXAC add  POBLACION       VARCHAR2(35);
alter table RECIBOS_EXAC add  PROVINCIA       VARCHAR2(35);
alter table RECIBOS_EXAC add  CODIGO_POSTAL   CHAR(5);

CREATE PUBLIC SYNONYM WriteTempExac FOR GIALNET.WriteTempExac;

-- 22 de agosto de 2001
ALTER TABLE IBI ADD COTITULARES CHAR(1) DEFAULT 'N' check (COTITULARES in ('S','N'));
ALTER TABLE IBI ADD IDDOMIALTER	 INTEGER;
ALTER TABLE IBI ADD REPRESENTANTE     CHAR(10);

ALTER TABLE IBI ADD CONSTRAINT IBIDOMIALTER
       FOREIGN KEY (IDDOMIALTER)
       REFERENCES DOMICILIOS_ALTERNATIVOS(ID);


alter table recibos_IBI add NIF             CHAR(10);
alter table recibos_IBI add POBLACION       VARCHAR2(35);
alter table recibos_IBI add PROVINCIA       VARCHAR2(35);
alter table recibos_IBI add CODIGO_POSTAL   CHAR(5);
alter table recibos_IBI add NOMBRE_TITULAR  VARCHAR(40);
alter table recibos_ibi add DOMI_TRIBUTARIO varchar2(50);

drop table IMP_RECIBOS_IBI;
CREATE TABLE IMP_RECIBOS_IBI;

CREATE PUBLIC SYNONYM WriteTempIBI FOR GIALNET.WriteTempIBI;
CREATE PUBLIC SYNONYM ADDDEL_IBI_REPRESENTANTE FOR GIALNET.ADDDEL_IBI_REPRESENTANTE;

CREATE PUBLIC SYNONYM ADDDEL_DOMIALTERNATIVOS FOR GIALNET.ADDDEL_DOMIALTERNATIVOS;

ALTER TABLE LIQUIDACIONES ADD COTITULARES CHAR(1) DEFAULT 'N' check (COTITULARES in ('S','N'));
ALTER TABLE LIQUIDACIONES ADD IDDOMIALTER	 INTEGER;
ALTER TABLE LIQUIDACIONES ADD CONSTRAINT LIQUIDOMIALTER
       FOREIGN KEY (IDDOMIALTER)
       REFERENCES DOMICILIOS_ALTERNATIVOS(ID);

CREATE INDEX LIQUINIF ON LIQUIDACIONES (NIF) TABLESPACE INDICES;
CREATE INDEX LIQUIGRUPO ON LIQUIDACIONES (GRUPO) TABLESPACE INDICES;
CREATE OR REPLACE VIEW VWLIQUI;

-- 23 DE AGOSTO DE 2001
drop PROCEDURE GENPAD_RUS81;
DROP PROCEDURE Imprime_Recibos_Rus_F;

ALTER TABLE Rus80 ADD COTITULARES CHAR(1) DEFAULT 'N' check (COTITULARES in ('S','N'));
ALTER TABLE Rus80 ADD IDDOMIALTER	 INTEGER;
ALTER TABLE Rus80 ADD REPRESENTANTE     CHAR(10);

ALTER TABLE Rus80 ADD CONSTRAINT RusticaDOMIALTER
       FOREIGN KEY (IDDOMIALTER)
       REFERENCES DOMICILIOS_ALTERNATIVOS(ID);


alter table RECIBOS_RUSTICA add NIF             CHAR(10);
alter table RECIBOS_RUSTICA add POBLACION       VARCHAR2(35);
alter table RECIBOS_RUSTICA add PROVINCIA       VARCHAR2(35);
alter table RECIBOS_RUSTICA add CODIGO_POSTAL   CHAR(5);
alter table RECIBOS_RUSTICA add NOMBRE_TITULAR  VARCHAR(40);
alter table RECIBOS_RUSTICA DROP CONSTRAINT RECRUSTIID81;
alter table RECIBOS_RUSTICA DROP CONSTRAINT CV_RECI_RUS;
--desde el schema manager quitar la constraint de id81 not null para que permita nulos;

alter table RECIBOS_RUSTICA ADD ABONADO INTEGER;

drop table IMP_RECIBOS_RUS;
CREATE TABLE IMP_RECIBOS_RUS;

CREATE PUBLIC SYNONYM WriteTempRustica FOR GIALNET.WriteTempRustica;
CREATE PUBLIC SYNONYM ADDDEL_RUSTICA_REPRESENTANTE FOR GIALNET.ADDDEL_RUSTICA_REPRESENTANTE;

--24 DE AGOSTO DE 2001
alter table multas add IDDOMIALTER	 INTEGER;
alter table multas add CONSTRAINT MULTASDOMIALTER
       FOREIGN KEY (IDDOMIALTER)
       REFERENCES DOMICILIOS_ALTERNATIVOS(ID);

CREATE SEQUENCE GEN_MULTAS INCREMENT BY 1 START WITH 1;
CREATE PUBLIC SYNONYM GEN_MULTAS FOR GIALNET.GEN_MULTAS;

ALTER TABLE MULTAS DROP PRIMARY KEY;
ALTER TABLE MULTAS ADD ID INTEGER;

CREATE PROCEDURE INSERTA_IDMULTAS AS
   xID INTEGER;
   CURSOR C1 IS SELECT MUNICIPIO,EXPEDIENTE FROM MULTAS;
BEGIN

   FOR v1 IN C1 LOOP
      SELECT GEN_MULTAS.NEXTVAL INTO xID FROM DUAL;
      UPDATE MULTAS SET ID=xID WHERE MUNICIPIO=v1.MUNICIPIO AND EXPEDIENTE=v1.EXPEDIENTE;
   END LOOP;   
END;
/
EXECUTE INSERTA_IDMULTAS;
DROP PROCEDURE INSERTA_IDMULTAS;

ALTER TABLE MULTAS MODIFY ID INTEGER NOT NULL;
ALTER TABLE MULTAS ADD PRIMARY KEY(ID);
ALTER TABLE MULTAS ADD CONSTRAINT MULTASEXPEMUNI UNIQUE (MUNICIPIO,EXPEDIENTE);
ALTER TABLE MULTAS ADD NUMERO_DE_CARGO CHAR(10);
ALTER TABLE MULTAS ADD F_CARGO DATE;
ALTER TRIGGER ESTADO_MOD_BOLETIN DISABLE;
ALTER TABLE MULTAS ADD PASADO CHAR(1) DEFAULT 'N';
ALTER TRIGGER ESTADO_MOD_BOLETIN ENABLE;

CREATE PUBLIC SYNONYM WRITE_MULTAS_PUNTEO FOR GIALNET.WRITE_MULTAS_PUNTEO;
CREATE PUBLIC SYNONYM MULTAS_PASE_RECA FOR GIALNET.MULTAS_PASE_RECA;


--27 de agosto de 2001
ALTER TABLE IAE ADD COTITULARES CHAR(1) DEFAULT 'N' check (COTITULARES in ('S','N'));
ALTER TABLE IAE ADD IDDOMIALTER INTEGER;
ALTER TABLE IAE ADD REPRESENTANTE CHAR(10);
ALTER TABLE IAE ADD CONSTRAINT IAEDOMIALTER
      FOREIGN KEY (IDDOMIALTER)
      REFERENCES DOMICILIOS_ALTERNATIVOS(ID);

ALTER TABLE RECIBOS_IAE ADD PROVINCIA VARCHAR2(35);
ALTER TABLE RECIBOS_IAE ADD CODPOSTAL_TRI	CHAR(5);
ALTER TABLE RECIBOS_IAE ADD POBLACION_TRI	CHAR(25);
ALTER TABLE RECIBOS_IAE ADD PROVINCIA_TRI	VARCHAR2(35);

DROP PROCEDURE CREAGRUPO_RECI_IAE;

CREATE PUBLIC SYNONYM WriteTempIAE FOR GIALNET.WriteTempIAE;
CREATE PUBLIC SYNONYM ADDDEL_IAE_REPRESENTANTE FOR GIALNET.ADDDEL_IAE_REPRESENTANTE;

CREATE INDEX IAENIF ON IAE (NIF) TABLESPACE INDICES;
CREATE INDEX IAENOMBRE ON IAE (NOMBRE) TABLESPACE INDICES;
CREATE INDEX IAEMUNIYEAR ON IAE (MUNICIPIO,YEAR) TABLESPACE INDICES;

-- 28 DE AGOSTO DEL 2001
CREATE INDEX PLUSIDXADQUI ON PLUSVALIAS (NIF_ADQUIRIENTE) TABLESPACE INDICES;
CREATE INDEX PLUSIDXADQUIREPRE ON PLUSVALIAS (NIF_REPRE_ADQUI) TABLESPACE INDICES;
CREATE INDEX PLUSIDXTRANS ON PLUSVALIAS (NIF_TRANSMITENTE) TABLESPACE INDICES;
CREATE INDEX PLUSIDXTRANSREPRE ON PLUSVALIAS (NIF_REPRE_TRANS) TABLESPACE INDICES;

ALTER TABLE PLUSVALIAS ADD IDDOMIALTER INTEGER;
ALTER TABLE PLUSVALIAS ADD COTITULARES CHAR(1) DEFAULT 'N' check (COTITULARES in ('S','N'));

--29 de agosto de 2001
CREATE or replace FUNCTION DameDomiAlternativo en 01_gt.sql;
CREATE PUBLIC SYNONYM DameDomiAlternativo FOR GIALNET.DameDomiAlternativo;
drop PROCEDURE EN_PLAZO_APREMIO;

ALTER TABLE AGUA ADD IDDOMIALTER INTEGER;
ALTER TABLE AGUA ADD COTITULARES CHAR(1) DEFAULT 'N' check (COTITULARES in ('S','N'));
CREATE OR REPLACE VIEW vwAGUA;


-- 30 DE AGOSTO DE 2001
DROP TABLE TABLA_EXAC;
CREATE TABLE TABLA_EXAC;
DROP TABLE TABLA_RECIBOS_EXAC;
CREATE TABLE TABLA_RECIBOS_EXAC;
drop PROCEDURE PROC_TABLA_RECIBOS_EXAC;
update programas set consulta_rec='SELECT * FROM RECIBOS_EXAC WHERE ID=:xID'
	where programa='EXACCIONES';

alter table programas add ID INTEGER DEFAULT 0;
update programas set id=1 where programa='LIQUIDACIO';
update programas set id=2 where programa='IBI';
update programas set id=3 where programa='IAE';
update programas set id=4 where programa='RUSTICA';
update programas set id=5 where programa='VEHICULOS';
update programas set id=6 where programa='EXACCIONES';
update programas set id=7 where programa='PLUSVALIA';
update programas set id=8 where programa='MULTAS';
update programas set id=9 where programa='VADOS';
update programas set id=10 where programa='REGISTRO';
update programas set id=11 where programa='AGUA';
ALTER TABLE PROGRAMAS ADD CONSTRAINT PROGRAMASID UNIQUE (ID);

DROP TABLE TABLA_PLUSVA;
CREATE TABLE TABLA_PLUSVA;

CREATE PUBLIC SYNONYM CAMBIA_ALLYEARWORK_LIQUI FOR GIALNET.CAMBIA_ALLYEARWORK_LIQUI;

--31 DE AGOSTO DE 2001
CREATE INDEX IBICODOPERACION ON IBI (CODIGO_OPERACION) TABLESPACE INDICES;
CREATE INDEX RUSCODOPERACION ON RUS80 (CODIGO_OPERACION) TABLESPACE INDICES;

CREATE INDEX IDXCOTITULARES ON 
	COTITULARES (ID_CONCEPTO,PROGRAMA) TABLESPACE INDICES;
CREATE INDEX IDXCOTITULARESREC ON 
	COTITULARES_RECIBO (AYTO,PADRON,YEAR,PERIODO,RECIBO) TABLESPACE INDICES;


CREATE PUBLIC SYNONYM ADDCOTITULARESREC FOR GIALNET.ADDCOTITULARESREC;
CREATE PUBLIC SYNONYM DELCOTITULARESREC FOR GIALNET.DELCOTITULARESREC;

--3 de Septiembre de 2001
CREATE OR REPLACE VIEW VWEXACCIONES en el archivo 01_GT.SQL;
CREATE OR REPLACE VIEW VWexacciones_contri en el archivo 01_GT.SQL;
CREATE OR REPLACE VIEW VWEXACCIONES_LISTADO en el archivo 01_GT.SQL;
CREATE OR REPLACE VIEW VWRECIBOS_EXAC_CONTRI en el archivo 01_GT.SQL;


alter table epigrafe drop CONSTRAINT CV_EPI;
alter table epigrafe add CONSTRAINT CV_EPI UNIQUE (EPIGRAFE,TIPO_ACTIVIDAD);

-- 5 DE SEPTIEMBRE DE 2001
ALTER TABLE LIQUIDACIONES ADD IDVALOR INTEGER;
ALTER TABLE HISTORIA_LIQUI DROP CONSTRAINT HISTOLIQLIQ;

/*************** A PARTIR DE AQUÍ SE CREA NUEVO PROYECTO PARA EL EURO  *******************/

-- 7 DE SEPTIEMBRE DE 2001
CREATE OR REPLACE PROCEDURE INSERTA_REGISTRO_IBI en el archivo 04_IBI.SQL;
DELETE FROM IMP_RECIBOS_IBI;
ALTER TABLE IMP_RECIBOS_IBI MODIFY xTOTAL FLOAT;

-- 10 DE SEPTIEMBRE DE 2001
CREATE OR REPLACE PROCEDURE ADD_LIQUI en el archivo 03_liquidaciones.sql;
CREATE OR REPLACE PROCEDURE IMPORTEENCADENA en el archivo 02_Varios.sql;
CREATE OR REPLACE PROCEDURE GENERA_PADRON_IBI en el archivo 04_IBI.sql;
delete from recibos_caixa;
alter table RECIBOS_CAIXA modify total float;
CREATE OR REPLACE PROCEDURE Proc_Caixa_IBI en el archivo 04_IBI.SQL;
CREATE OR REPLACE PROCEDURE CUADERNO19_IBI en el archivo 04_IBI.SQL;
CREATE OR REPLACE PROCEDURE INSERTA_RECIBO_FICTICIO en el archivo 02_VARIOS.SQL;

-- 12 DE SEPTIEMBRE DE 2001
CREATE OR REPLACE PROCEDURE INSER_MOD_TAR_VEHI en el archivo 06_VEHICULOS.SQL;
CREATE OR REPLACE PROCEDURE GENERA_PADRON_VEHI en el archivo 06_VEHICULOS.SQL;

CREATE OR REPLACE PROCEDURE INSERTA_RUSTICA_DETALLE en el archivo 08_RUSTICA.SQL;
CREATE OR REPLACE PROCEDURE INSERTA_REGISTRO_RUSTICA en el archivo 08_RUSTICA.SQL;
CREATE OR REPLACE PROCEDURE GENERA_PADRON_RUS en el archivo 08_RUSTICA.SQL;
CREATE OR REPLACE PROCEDURE RUS_PASE_RECA en el archivo 08_RUSTICA.SQL;

-- 13 de Septiembre de 2001
CREATE OR REPLACE PROCEDURE WriteTempIBI en el archivo 04_IBI.SQL;
DELETE FROM RECIBOS_CUADERNO19;
ALTER TABLE RECIBOS_CUADERNO19 MODIFY TOTAL FLOAT;
CREATE OR REPLACE PROCEDURE CUADERNO19_IBI en el archivo 04_IBI.SQL;

CREATE OR REPLACE PROCEDURE GENERA_PADRON_IAE en el archivo 05_IAE.SQL;
CREATE OR REPLACE PROCEDURE INSERTA_REGISTRO_IAE en el archivo 05_IAE.SQL;
CREATE OR REPLACE PROCEDURE Proc_Caixa_IAE en el archivo 05_IAE.SQL;
CREATE OR REPLACE PROCEDURE CUADERNO19_IAE en el archivo 05_IAE.SQL;

CREATE OR REPLACE PROCEDURE MOD_LIQUI en el archivo 03_LIQUIDACIONES.SQL;
CREATE OR REPLACE PROCEDURE ADD_LIQUI_TEMP en el archivo 03_LIQUIDACIONES.SQL;
CREATE OR REPLACE PROCEDURE REPONER_LIQUI en el archivo 03_LIQUIDACIONES.SQL;

CREATE OR REPLACE PROCEDURE INSERTA_PLUSVALIA en el archivo 09_PLUSVALIAS.SQL;
CREATE OR REPLACE PROCEDURE MODIFICA_PLUSVALIA en el archivo 09_PLUSVALIAS.SQL;

-- 14 de Septiembre de 2001
DELETE FROM IMP_RECIBOS_IAE;
ALTER TABLE IMP_RECIBOS_IAE MODIFY TOTAL FLOAT;
CREATE OR REPLACE PROCEDURE WriteTempIAE en el archivo 05_IAE.SQL;

DROP TABLE IMP_ETIQUETAS;
CREATE TABLE IMP_ETIQUETAS;
DROP TABLE TABLA_PLUSVA;
CREATE TABLE TABLA_PLUSVA;
CREATE OR REPLACE PROCEDURE Imprimir_Etiquetas en el archivo 09_PLUSVALIAS.SQL;
CREATE OR REPLACE PROCEDURE PROC_TABLA_PLUSVA en el archivo 09_PLUSVALIAS.SQL;
DELETE FROM IMP_RECIBOS_VEHI;
ALTER TABLE IMP_RECIBOS_VEHI MODIFY TOTAL FLOAT;
DELETE FROM IMP_RECIBOS_RUS;
ALTER TABLE IMP_RECIBOS_RUS MODIFY XTOTAL FLOAT;

CREATE OR REPLACE PROCEDURE CUADERNO19_RUSTICA en el archivo 08_RUSTICA.SQL;
CREATE OR REPLACE PROCEDURE Proc_Caixa_Rustica en el archivo 08_RUSTICA.SQL;
CREATE OR REPLACE PROCEDURE WriteTempRustica en el archivo 08_RUSTICA.SQL;

-- 17 de Septiembre de 2001
CREATE OR REPLACE PROCEDURE InsertaBoletin en el archivo 12_MULTAS.SQL;
CREATE OR REPLACE PROCEDURE ModificaBoletin en el archivo 12_MULTAS.SQL;
CREATE OR REPLACE PROCEDURE InsertaSancion en el archivo 12_MULTAS.SQL;

CREATE OR REPLACE PROCEDURE PASA_A_DBASE en el archivo 12_MULTAS.SQL;
CREATE OR REPLACE PROCEDURE PASA_EXPEDIENTE_DBASE en el archivo 12_MULTAS.SQL;

ALTER TABLE MULTAS MODIFY IMPORTE FLOAT DEFAULT 0.00;
ALTER TABLE MULTAS DROP COLUMN EUROS;

DELETE FROM PASAR_DBASE;
ALTER TABLE PASAR_DBASE MODIFY xIMPORTE FLOAT;
ALTER TABLE PASAR_DBASE MODIFY xOtroImporte FLOAT;

DELETE FROM IMP_RECIBOS_AGUA;
ALTER TABLE IMP_RECIBOS_AGUA MODIFY TOTAL FLOAT;
ALTER TABLE IMP_RECIBOS_AGUA MODIFY IMPORTE1 FLOAT;
ALTER TABLE IMP_RECIBOS_AGUA MODIFY IMPORTE2 FLOAT;
ALTER TABLE IMP_RECIBOS_AGUA MODIFY IMPORTE3 FLOAT;
ALTER TABLE IMP_RECIBOS_AGUA MODIFY IMPORTE4 FLOAT;
ALTER TABLE IMP_RECIBOS_AGUA MODIFY IMPORTE5 FLOAT;
ALTER TABLE IMP_RECIBOS_AGUA MODIFY IMPORTE6 FLOAT;
ALTER TABLE IMP_RECIBOS_AGUA MODIFY IMPORTE7 FLOAT;


CREATE OR REPLACE PROCEDURE SUBTOTALES en 17_AGUAS_EMISION_DE_RECIBOS.SQL
CREATE OR REPLACE PROCEDURE DAME_DATOS en 17_AGUAS_EMISION_DE_RECIBOS.SQL
CREATE OR REPLACE PROCEDURE Imprime_Recibos_Agua en 17_AGUAS_EMISION_DE_RECIBOS.SQL
CREATE OR REPLACE PROCEDURE ESPECIAL_LINEAS_RECIBO en 17_AGUAS_EMISION_DE_RECIBOS.SQL
CREATE OR REPLACE PROCEDURE MODIFICA_UN_RECIBO_AGUA en 17_AGUAS_EMISION_DE_RECIBOS.SQL

CREATE OR REPLACE PROCEDURE Inserta_Abonados_Agua en 15_AGUAS_ALTA_ABONADOS.SQL
CREATE OR REPLACE PROCEDURE Modifica_Abonados_Agua en 15_AGUAS_ALTA_ABONADOS.SQL

CREATE OR REPLACE VIEW VWLIQUI 
CREATE OR REPLACE VIEW TABLA_LIQUIDACIONES 

CREATE OR REPLACE PROCEDURE CUOTA_VARIABLE_BLOQUES en 16_AGUAS_LINEAS_RECIBO.SQL;
CREATE OR REPLACE PROCEDURE CALCULA_LINEAS_RECIBO en 16_AGUAS_LINEAS_RECIBO.SQL;
CREATE OR REPLACE PROCEDURE GEN_RECIBOS_AGUA en 17_AGUAS_EMISION_DE_RECIBOS.SQL;

DELETE FROM TABLA_LISTADO_PADRON;
ALTER TABLE TABLA_LISTADO_PADRON MODIFY X1 FLOAT DEFAULT 0;
ALTER TABLE TABLA_LISTADO_PADRON MODIFY X2 FLOAT DEFAULT 0;
ALTER TABLE TABLA_LISTADO_PADRON MODIFY X3 FLOAT DEFAULT 0;
ALTER TABLE TABLA_LISTADO_PADRON MODIFY X4 FLOAT DEFAULT 0;
ALTER TABLE TABLA_LISTADO_PADRON MODIFY X5 FLOAT DEFAULT 0;
ALTER TABLE TABLA_LISTADO_PADRON MODIFY X6 FLOAT DEFAULT 0;
ALTER TABLE TABLA_LISTADO_PADRON MODIFY X7 FLOAT DEFAULT 0;

CREATE OR REPLACE PROCEDURE Listado_Padron_Agua en 17_AGUAS_EMISION_DE_RECIBOS.SQL;
CREATE OR REPLACE PROCEDURE Proc_Caixa_Agua en 17_AGUAS_EMISION_DE_RECIBOS.SQL;
CREATE OR REPLACE PROCEDURE Cuaderno19_Agua en 17_AGUAS_EMISION_DE_RECIBOS.SQL;
CREATE OR REPLACE PROCEDURE AGUA_PASE_RECA en 17_AGUAS_EMISION_DE_RECIBOS.SQL;

-- 18 de Septiembre de 2001

CREATE OR REPLACE PROCEDURE PASE_DIPUTACION_AGUA en 17_AGUAS_EMISION_DE_RECIBOS.SQL;
CREATE OR REPLACE PROCEDURE ADD_TARIFA_AGUA en 18_AGUAS.SQL

DELETE FROM ESTADISTICASGT;
ALTER TABLE ESTADISTICASGT MODIFY IMPORTE FLOAT DEFAULT 0;

DELETE FROM CONFIG_BLOQUES;
ALTER TABLE CONFIG_BLOQUES MODIFY IMPORTE FLOAT DEFAULT 0;

DELETE FROM PRECIOS_BLOQUES;
ALTER TABLE PRECIOS_BLOQUES MODIFY IMPORTE FLOAT DEFAULT 0;

CREATE OR REPLACE PROCEDURE CALCULA_BLOQUES_ESTA en 19_AGUAS_ESTADISTICAS.SQL;
CREATE OR REPLACE PROCEDURE RELLENA_PRECIO_BLOQUES en 19_AGUAS_ESTADISTICAS.SQL;


-- 20 de Septiembre de 2001

-- IMPORTANTE: Realizar los pasos del archivo EURO_EXAC.SQL 
-- para el cambio de la tabla EXACCIONES. CREATE TABLE EXACCIONES (en EURO_EXAC.SQL)

CREATE OR REPLACE VIEW VWEXAC	
CREATE OR REPLACE VIEW VWEXACCIONES en el archivo 01_GT.SQL; 
CREATE OR REPLACE VIEW VWexacciones_LISTADO 
-- Lanzar el archivo 13_EXACCIONES.SQL;

CREATE OR REPLACE PROCEDURE Proc_Caixa_IBI en el archivo 04_IBI.SQL;
CREATE OR REPLACE PROCEDURE CUADERNO19_IAE en el archivo 05_IAE.SQL;
CREATE OR REPLACE PROCEDURE Proc_Caixa_IAE en el archivo 05_IAE.SQL;
CREATE OR REPLACE PROCEDURE CUADERNO19_VEHI en el archivo 06_VEHICULOS.SQL;
CREATE OR REPLACE PROCEDURE Proc_Caixa_Vehi en el archivo 06_VEHICULOS.SQL;
CREATE OR REPLACE PROCEDURE Proc_Caixa_Rustica en el archivo 08_RUSTICA.SQL;
CREATE OR REPLACE PROCEDURE Proc_Caixa_EXAC en el archivo 13_EXACCIONES.SQL;
CREATE OR REPLACE PROCEDURE Cuaderno19_Agua en el archivo 17_AGUAS_EMISION_DE_RECIBOS.SQL;
CREATE OR REPLACE PROCEDURE Proc_Caixa_Agua en el archivo 17_AGUAS_EMISION_DE_RECIBOS.SQL;

ALTER TABLE SANCION ADD DESCUENTO FLOAT DEFAULT 20;

-- 15 de Octubre de 2001

CREATE OR REPLACE PROCEDURE Imprime_Recibos_Agua en el archivo 17_AGUAS_EMISION_DE_RECIBOS.SQL.

CREATE OR REPLACE PROCEDURE INSERTA_RECIBO_FICTICIO en 02_varios.sql;

CREATE OR REPLACE VIEW VWEXACCIONES en 01_GT.SQL;
CREATE OR REPLACE VIEW VWexacciones_LISTADO en 01_GT.SQL;
CREATE OR REPLACE VIEW VWRECIBOS_EXAC_CONTRI en 01_GT.SQL;

CREATE TABLE DOCMULTA en 01_GT.SQL;
CREATE PUBLIC SYNONYM DOCMULTA FOR GIALNET.DOCMULTA;
CREATE OR REPLACE PROCEDURE ADDMOD_DOCUMULTA en el archivo 12_MULTAS.SQL;
CREATE PUBLIC SYNONYM ADDMOD_DOCUMULTA FOR GIALNET.ADDMOD_DOCUMULTA;

CREATE OR REPLACE TRIGGER ESTADO_MOD_BOLETIN en 21_TRIGGERS_GT_ORACLE.SQL

CREATE SEQUENCE GENDOCUMULTA INCREMENT BY 1 START WITH 1; en 01_SECUENCIAS.SQL
CREATE PUBLIC SYNONYM GENDOCUMULTA FOR GIALNET.GENDOCUMULTA;
CREATE OR REPLACE TRIGGER T_INS_DOCUMULTA en 21_TRIGGERS_GT_ORACLE.SQL
CREATE PUBLIC SYNONYM T_INS_DOCUMULTA FOR GIALNET.T_INS_DOCUMULTA;

lanzar las tablas relacionadas con la Inspección en el archivo 01_GT.SQL;
CREATE PUBLIC SYNONYM INSPECCIONES FOR GIALNET.INSPECCIONES;
CREATE PUBLIC SYNONYM VWINSPE FOR GIALNET.VWINSPE;
CREATE PUBLIC SYNONYM SEGUIMIENTO_INSPE FOR GIALNET.SEGUIMIENTO_INSPE;
CREATE PUBLIC SYNONYM VWSEGUINSPE FOR GIALNET.VWSEGUINSPE;
CREATE PUBLIC SYNONYM DOCSEGUI FOR GIALNET.DOCSEGUI;
CREATE PUBLIC SYNONYM NOTIFICACIONES_INSPE FOR GIALNET.NOTIFICACIONES_INSPE;

CREATE SEQUENCE GENINSPE INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE GENSEGUIINSPE INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE GENDOCINSPE INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE GENNOTIINSPE INCREMENT BY 1 START WITH 1;

CREATE PUBLIC SYNONYM GENINSPE FOR GIALNET.GENINSPE;
CREATE PUBLIC SYNONYM GENSEGUIINSPE FOR GIALNET.GENSEGUIINSPE;
CREATE PUBLIC SYNONYM GENDOCINSPE FOR GIALNET.GENDOCINSPE;
CREATE PUBLIC SYNONYM GENNOTIINSPE FOR GIALNET.GENNOTIINSPE;

lanzar el archivo 25_INSPECCIONES.SQL;
lanzar el archivo 26_TRIGGERS_INSPECCIONES.SQL;

CREATE PUBLIC SYNONYM ADD_INSPECCION FOR GIALNET.ADD_INSPECCION;		
CREATE PUBLIC SYNONYM MODIFY_INSPECCION FOR GIALNET.MODIFY_INSPECCION;		
CREATE PUBLIC SYNONYM ADD_SEGUIMIENTO_INSPE FOR ADD_GIALNET.SEGUIMIENTO_INSPE;
CREATE PUBLIC SYNONYM MODIFY_SEGUIMIENTO_INSPE FOR MODIFY_GIALNET.SEGUIMIENTO_INSPE;
CREATE PUBLIC SYNONYM ADD_DOCSEGUI FOR GIALNET.ADD_DOCSEGUI;
CREATE PUBLIC SYNONYM WRITEACUSE_INSPE FOR GIALNET.WRITEACUSE_INSPE;
CREATE PUBLIC SYNONYM PUBLICAR_INSPE_BOP FOR GIALNET.PUBLICAR_INSPE_BOP;
CREATE PUBLIC SYNONYM PON_FECHA_BOP_INSPE FOR GIALNET.PON_FECHA_BOP_INSPE;

CREATE TABLE DATOS_REGISTRO_DEPAR en el archivo 01_GT.SQL;
CREATE PUBLIC SYNONYM DATOS_REGISTRO_DEPAR FOR GIALNET.DATOS_REGISTRO_DEPAR;
INSERT INTO DATOS_REGISTRO_DEPAR (DEPARTAMENTO) SELECT DEPARTAMENTO FROM DEPARTAMENTO;

ALTER TABLE LIBRO_DE_REGISTRO ADD NUM_REGISTRO_DEPAR	CHAR(12);

DROP TABLE TABLA_AUX_LIBRO_REGISTRO;
CREATE TABLE TABLA_AUX_LIBRO_REGISTRO en el archivo 01_GT.SQL;
DROP TABLE TABLA_AUX_TABLA_REGISTRO;
CREATE TABLE TABLA_AUX_TABLA_REGISTRO en el archivo 01_GT.SQL;

create or replace procedure libro_registro en el archivo 600_REGISTRO.SQL; (RECA)
CREATE OR REPLACE PROCEDURE TABLA_REGISTRO en el archivo 600_REGISTRO.SQL; (RECA)
CREATE OR REPLACE TRIGGER T_INS_LIBRO_DE_REGISTRO en el archivo 600_REGISTRO.SQL; (RECA)
CREATE OR REPLACE PROCEDURE REGISTRO_ADD_MOD_ENTRADA en el archivo 600_REGISTRO.SQL; (RECA)
CREATE OR REPLACE PROCEDURE SET_YEAR en el archivo 600_REGISTRO.SQL; (RECA)

CREATE OR REPLACE TRIGGER T_ADD_MOD_DEPA en el archivo 600_REGISTRO.SQL; (RECA)

--Restricción asociada al check de tipoconecta;
ALTER TABLE LIBRO_DE_REGISTRO DROP CONSTRAINT ¿¿SYS_C001181??;  
ALTER TABLE LIBRO_DE_REGISTRO ADD
    ( CONSTRAINT SYS_C001181 CHECK (TIPOCONECTA IN ('V','G','E','I')));



DROP TABLE PASAR_DBASE;
CREATE TABLE PASAR_DBASE EN 01_GT.SQL
LANZAR EL ARCHIVO 12_MULTAS.SQL ENTERO.
UPDATE DATOSPER SET DESCUENTO=30,DENUNCIA=120,SANCION=180;

-- 19 de Octubre de 2001

CREATE INDEX INDXNIFAGUA ON 
	AGUA (NIF) TABLESPACE INDICES;

CREATE INDEX INDXRECIAGUA ON 
	RECIBOS_AGUA (MUNICIPIO,YEAR,PERIODO) TABLESPACE INDICES;

CREATE INDEX INDXDESGLOAGUA ON 
	DESGLOSE_AGUAS (MUNICIPIO,YEAR,PERIODO,ABONADO) TABLESPACE INDICES;


CREATE OR REPLACE PROCEDURE GetDomicilioFiscal en el archivo 02_CONTRIBUYENTES.SQL;

-- 22 de Octubre de 2001
DROP TABLE IMP_RECIBOS_AGUA;
CREATE TABLE IMP_RECIBOS_AGUA EN 01_GT.SQL
Lanzar archivo 17_AGUAS_EMISION_DE_RECIBOS.SQL;


-- 24 DE OCTUBRE DE 2001
CREATE OR REPLACE PROCEDURE PASA_A_DBASE en 12_MULTAS.SQL;
CREATE OR REPLACE PROCEDURE PASA_EXPEDIENTE_DBASE EN 12_MULTAS.SQL;

-- 29 de Octubre de 2001
CREATE OR REPLACE PROCEDURE INSERTA_REGISTRO_RUSTICA en el archivo 08_RUSTICA.SQL;

-- 30 de Octubre de 2001
CREATE OR REPLACE VIEW VWEXACCIONES en el archivo 01_GT.SQL;
CREATE OR REPLACE VIEW VWexacciones_LISTADO en el archivo 01_GT.SQL;

-- 19 de Noviembre de 2001
CREATE OR REPLACE PROCEDURE MOD_LIQUI en el archivo 03_LIQUIDACIONES.SQL;
CREATE OR REPLACE TRIGGER T_UPD_LIQUIDACIONES en el archivo 03_LIQUIDACIONES_TRIGGERS.SQL;
CREATE OR REPLACE TRIGGER T_UPD_PLUSVALIAS en el archivo 21_TRIGGERS_GTORACLE;

CREATE VIEW VWIMPRIMEINSPE en el archivo 01_GT.SQL;
CREATE PUBLIC SYNONYM VWIMPRIMEINSPE FOR GIALNET.VWIMPRIMEINSPE;

CREATE OR REPLACE PROCEDURE INSERTAVEHICULO en el archivo 06_vehiculos.sql;
CREATE OR REPLACE PROCEDURE MODIFICAVEHICULO en el archivo 06_vehiculos.sql;

--26 DE NOVIEMBRE 2001 ANTONIO
ALTER TABLE CONTRIBUYENTES ADD VALIDADO	CHAR(1) DEFAULT 'N' check (VALIDADO in ('S','G','N'));
ALTER TABLE CONTRIBUYENTES ADD PERSONALIDAD CHAR(1) DEFAULT 'F' CHECK (PERSONALIDAD IN ('F','J'));

-- 28 de Noviembre de 2001
ALTER TABLE DATOSPER ADD YEAR_LAST_PONENCIA CHAR(4);
ALTER TABLE DATOSPER ADD YEARS_PRORRATEO INTEGER DEFAULT 10;

-- 30 de Noviembre de 2001
ALTER TABLE IBI ADD YEAR_INI_BONI CHAR(4) DEFAULT '0000';
ALTER TABLE IBI ADD MES_INI_BONI CHAR(2) DEFAULT '00';
CREATE OR REPLACE PROCEDURE IBI_BONIFI en el archivo 04_IBI.SQL;
CREATE OR REPLACE VIEW VWIBI en el archivo 01_GT.SQL;

-- 20 de Diciembre de 2001
alter table RECIBOS_AGUA add  POBLACION       VARCHAR(35);
alter table RECIBOS_AGUA add  PROVINCIA       VARCHAR(35);
alter table RECIBOS_AGUA add  CODIGO_POSTAL   CHAR(5);

DROP TABLE TABLA_PASE_DIPUTACION;
CREATE TABLE TABLA_PASE_DIPUTACION en el archivo 01_GT.SQL;

CREATE OR REPLACE PROCEDURE GEN_RECIBOS_AGUA en el archivo 17_AGUAS_EMISION_DE_RECIBOS.SQL;
CREATE OR REPLACE PROCEDURE PASE_DIPUTACION_AGUA en el archivo 17_AGUAS_EMISION_DE_RECIBOS.SQL;

/************************* actualizado hasta aqui para ATECO ********************************/



