CREATE OR REPLACE PROCEDURE ADDLINEASPLA (
   	 xAYTO CHAR,
   	 xCONCEPTO CHAR
)
AS

BEGIN
   INSERT INTO LINEASPLA(AYTO, CONCEPTO, TITULO,TMANUAL)
   VALUES (xAYTO,xCONCEPTO,'ID','S');
  
   INSERT INTO LINEASPLA(AYTO, CONCEPTO, TITULO,TMANUAL)
   VALUES (xAYTO,xCONCEPTO,'ABONADO','N');

   INSERT INTO LINEASPLA(AYTO, CONCEPTO, TITULO,TMANUAL,LONGITUD)
   VALUES (xAYTO,xCONCEPTO,'AYTO','S',3);

   INSERT INTO LINEASPLA(AYTO, CONCEPTO, TITULO,TMANUAL,LONGITUD)
   VALUES (xAYTO,xCONCEPTO,'CONCEPTO','S',6);

   INSERT INTO LINEASPLA(AYTO, CONCEPTO, TITULO,TMANUAL,LONGITUD)
   VALUES (xAYTO,xCONCEPTO,'YEAR','S',4);

   INSERT INTO LINEASPLA(AYTO, CONCEPTO, TITULO,TMANUAL,LONGITUD)
   VALUES (xAYTO,xCONCEPTO,'PERIODO','S',2);
   
   INSERT INTO LINEASPLA(AYTO, CONCEPTO, TITULO,TMANUAL,LONGITUD)
   VALUES (xAYTO,xCONCEPTO,'NIF','N',10);

   INSERT INTO LINEASPLA(AYTO, CONCEPTO, TITULO,TMANUAL,LONGITUD)
   VALUES (xAYTO,xCONCEPTO,'NOMBRE','N',40);

   INSERT INTO LINEASPLA(AYTO, CONCEPTO, TITULO,TMANUAL,LONGITUD)
   VALUES (xAYTO,xCONCEPTO,'NIF_A_FACTURAR','N',10);

   INSERT INTO LINEASPLA(AYTO, CONCEPTO, TITULO,TMANUAL,LONGITUD)
   VALUES (xAYTO,xCONCEPTO,'DOMICILIADO','N',1);

   INSERT INTO LINEASPLA(AYTO, CONCEPTO, TITULO,TMANUAL,LONGITUD)
   VALUES (xAYTO,xCONCEPTO,'DNI_TITULAR','N',10);

   INSERT INTO LINEASPLA(AYTO, CONCEPTO, TITULO,TMANUAL,LONGITUD)
   VALUES (xAYTO,xCONCEPTO,'NOMBRE_TITULAR','N',40);

   INSERT INTO LINEASPLA(AYTO, CONCEPTO, TITULO,TMANUAL,LONGITUD)
   VALUES (xAYTO,xCONCEPTO,'ENTIDAD','N',4);

   INSERT INTO LINEASPLA(AYTO, CONCEPTO, TITULO,TMANUAL,LONGITUD)
   VALUES (xAYTO,xCONCEPTO,'SUCURSAL','N',4);

   INSERT INTO LINEASPLA(AYTO, CONCEPTO, TITULO,TMANUAL,LONGITUD)
   VALUES (xAYTO,xCONCEPTO,'DC','N',2);

   INSERT INTO LINEASPLA(AYTO, CONCEPTO, TITULO,TMANUAL,LONGITUD)
   VALUES (xAYTO,xCONCEPTO,'CUENTA','N',10);

   INSERT INTO LINEASPLA(AYTO, CONCEPTO, TITULO,TMANUAL,LONGITUD)
   VALUES (xAYTO,xCONCEPTO,'ESTADO_BANCO','N',2);

   INSERT INTO LINEASPLA(AYTO, CONCEPTO, TITULO,TMANUAL)
   VALUES (xAYTO,xCONCEPTO,'DESDE','N');
  
   INSERT INTO LINEASPLA(AYTO, CONCEPTO, TITULO,TMANUAL)
   VALUES (xAYTO,xCONCEPTO,'HASTA','N');

   INSERT INTO LINEASPLA(AYTO, CONCEPTO, TITULO,TMANUAL,LONGITUD)
   VALUES (xAYTO,xCONCEPTO,'REFERENCIA','N',10);

   INSERT INTO LINEASPLA(AYTO, CONCEPTO, TITULO,TMANUAL,LONGITUD)
   VALUES (xAYTO,xCONCEPTO,'DIGITO_CONTROL','N',2);

   INSERT INTO LINEASPLA(AYTO, CONCEPTO, TITULO,TMANUAL,LONGITUD)
   VALUES (xAYTO,xCONCEPTO,'TRIBUTO','N',3);

   INSERT INTO LINEASPLA(AYTO, CONCEPTO, TITULO,TMANUAL,LONGITUD)
   VALUES (xAYTO,xCONCEPTO,'EJERCICIO','N',2);

   INSERT INTO LINEASPLA(AYTO, CONCEPTO, TITULO,TMANUAL,LONGITUD)
   VALUES (xAYTO,xCONCEPTO,'REMESA','N',2);

   INSERT INTO LINEASPLA(AYTO, CONCEPTO, TITULO,TMANUAL,LONGITUD)
   VALUES (xAYTO,xCONCEPTO,'IMPORTE','N',12);

   INSERT INTO LINEASPLA(AYTO, CONCEPTO, TITULO, TMANUAL,LONGITUD)
   VALUES (xAYTO,xCONCEPTO,'EMISOR','N',6);

   INSERT INTO LINEASPLA(AYTO, CONCEPTO, TITULO,TMANUAL,LONGITUD)
   VALUES (xAYTO,xCONCEPTO,'CALLE','N',35);

   INSERT INTO LINEASPLA(AYTO, CONCEPTO, TITULO,TMANUAL,LONGITUD)
   VALUES (xAYTO,xCONCEPTO,'NUMERO','N',3);

   INSERT INTO LINEASPLA(AYTO, CONCEPTO, TITULO,TMANUAL,LONGITUD)
   VALUES (xAYTO,xCONCEPTO,'BLOQUE','N',1);

   INSERT INTO LINEASPLA(AYTO, CONCEPTO, TITULO,TMANUAL,LONGITUD)
   VALUES (xAYTO,xCONCEPTO,'ESCALERA','N',1);

   INSERT INTO LINEASPLA(AYTO, CONCEPTO, TITULO,TMANUAL,LONGITUD)
   VALUES (xAYTO,xCONCEPTO,'PLANTA','N',2);

   INSERT INTO LINEASPLA(AYTO, CONCEPTO, TITULO,TMANUAL,LONGITUD)
   VALUES (xAYTO,xCONCEPTO,'PISO','N',2);

   INSERT INTO LINEASPLA(AYTO, CONCEPTO, TITULO,TMANUAL,LONGITUD)
   VALUES (xAYTO,xCONCEPTO,'LETRA','N',2);

   INSERT INTO LINEASPLA(AYTO, CONCEPTO, TITULO,TMANUAL,LONGITUD)
   VALUES (xAYTO,xCONCEPTO,'CONCEPTO01','X',50);
  
   INSERT INTO LINEASPLA(AYTO, CONCEPTO, TITULO,TMANUAL,LONGITUD)
   VALUES (xAYTO,xCONCEPTO,'CONCEPTO02','X',50);

   INSERT INTO LINEASPLA(AYTO, CONCEPTO, TITULO,TMANUAL,LONGITUD)
   VALUES (xAYTO,xCONCEPTO,'CONCEPTO03','X',50);

   INSERT INTO LINEASPLA(AYTO, CONCEPTO, TITULO,TMANUAL,LONGITUD)
   VALUES (xAYTO,xCONCEPTO,'CONCEPTO04','X',50);

   INSERT INTO LINEASPLA(AYTO, CONCEPTO, TITULO,TMANUAL,LONGITUD)
   VALUES (xAYTO,xCONCEPTO,'CONCEPTO05','X',50);

   INSERT INTO LINEASPLA(AYTO, CONCEPTO, TITULO,TMANUAL,LONGITUD)
   VALUES (xAYTO,xCONCEPTO,'CONCEPTO06','X',50);

   INSERT INTO LINEASPLA(AYTO, CONCEPTO, TITULO,TMANUAL,LONGITUD)
   VALUES (xAYTO,xCONCEPTO,'CONCEPTO07','X',50);
  
   INSERT INTO LINEASPLA(AYTO, CONCEPTO, TITULO,TMANUAL,LONGITUD)
   VALUES (xAYTO,xCONCEPTO,'CONCEPTO08','X',50);

   INSERT INTO LINEASPLA(AYTO, CONCEPTO, TITULO,TMANUAL,LONGITUD)
   VALUES (xAYTO,xCONCEPTO,'CONCEPTO09','X',50);
  
   INSERT INTO LINEASPLA(AYTO, CONCEPTO, TITULO,TMANUAL,LONGITUD)
   VALUES (xAYTO,xCONCEPTO,'CONCEPTO10','X',50);
  
   INSERT INTO LINEASPLA(AYTO, CONCEPTO, TITULO,TMANUAL,LONGITUD)
   VALUES (xAYTO,xCONCEPTO,'CONCEPTO11','X',50);

END;
/

CREATE OR REPLACE PROCEDURE ADDPLANTILLA (
 	 xAYTO IN CHAR,
       xCONCEPTO IN CHAR,
       xDESCRIPCION IN CHAR,
	 xSI OUT INTEGER
)
AS

   CONTADOR INTEGER;

BEGIN
   xSI:=0;
   SELECT COUNT(*) INTO CONTADOR FROM PLANTILLAS 
   WHERE AYTO=xAYTO AND CONCEPTO=xCONCEPTO;

   IF CONTADOR=0 THEN
      INSERT INTO PLANTILLAS 
	  (AYTO,CONCEPTO,DESCRIPCION) 
      VALUES 
	  (xAYTO,xCONCEPTO,xDESCRIPCION);
      xSI:=1; 
   END IF;
END;
/


CREATE OR REPLACE PROCEDURE MODIFICAR_RECIBO_GENERICO (
       xID IN INTEGER,
       xNIF IN CHAR,
       xNOMBRE IN VARCHAR2,
       xCALLE IN VARCHAR2,
       xNUMERO IN VARCHAR2,
       xBLOQUE IN CHAR,
       xESCALERA IN CHAR,
       xPLANTA IN VARCHAR2,
       xPISO IN VARCHAR2,
       xLETRA IN VARCHAR2,
       xCODPOSTAL IN CHAR,
       xPOBLACION IN VARCHAR2,
       xDOMICILIADO IN CHAR,
       xNIFT IN CHAR,
       xNOMBRET IN VARCHAR2,
       xENTIDAD IN CHAR,
       xSUCURSAL IN CHAR,
       xDC IN CHAR,
       xCUENTA IN CHAR,
       xESTADO IN CHAR,
       xDESDE IN DATE,
       xHASTA IN DATE,
       xNOTIFICADO IN CHAR,
       xFECHANOTIF IN DATE,
       xVOLEJE IN CHAR,
       xFECHACARGO IN DATE,
       xCARGO IN CHAR,
       xCINICIAL IN FLOAT,
       xPRINCIPAL IN FLOAT,
       xRECARGO_O_E IN FLOAT,
       xRECARGO IN FLOAT,
       xCOSTAS IN FLOAT,
       xDEMORA IN FLOAT,
       xENTREGAS IN FLOAT,
       xREFERENCIA IN CHAR,
       xDC60 IN CHAR,
       xTRIBUTO IN CHAR,
       xEJERCICIO IN CHAR,
       xREMESA IN CHAR,
       xIMPORTE IN CHAR,
       xEMISOR IN CHAR,
       xCALLET IN VARCHAR2,
       xNUMEROT IN VARCHAR2,
       xBLOQUET IN CHAR,
       xESCALERAT IN CHAR,
       xPLANTAT IN VARCHAR2,
       xPISOT IN VARCHAR2,
       xLETRAT IN VARCHAR2,
       xCODPOSTALT IN CHAR,
       xPOBLACIONT IN VARCHAR2,
       xVAR1 IN VARCHAR2,
       xVAR2 IN VARCHAR2,
       xVAR3 IN VARCHAR2,
       xVAR4 IN VARCHAR2,
       xVAR5 IN VARCHAR2,
       xVAR6 IN VARCHAR2,
       xVAR7 IN VARCHAR2,
       xVAR8 IN VARCHAR2,
       xVAR9 IN VARCHAR2,
       xVAR10 IN VARCHAR2,
       xVAR11 IN VARCHAR2
)
AS

xYEAR  CHAR(4);
xDESDEAUX DATE;
xHASTAAUX DATE;
xFECHANOTIFAUX DATE;
xFECHACARGOAUX DATE;

BEGIN
  xDESDEAUX:=xDESDE;
  xYEAR:=TO_CHAR(xDESDE,'YYYY');
  
  IF xYEAR='1899' THEN
     xDESDEAUX:=NULL;
  END IF;

  xHASTAAUX:=xHASTA;
  xYEAR:=TO_CHAR(xHASTA,'YYYY');

  IF xYEAR='1899' THEN
     xHASTAAUX:=NULL;
  END IF;

  xFECHANOTIFAUX:=xFECHANOTIF;
  xYEAR:=TO_CHAR(xFECHANOTIF,'YYYY');

  IF xYEAR='1899' THEN
     xFECHANOTIFAUX:=NULL;
  END IF;

  xFECHACARGOAUX:=xFECHACARGO;
  xYEAR:=TO_CHAR(xFECHACARGO,'YYYY');
  
  IF xYEAR='1899' THEN
     xFECHACARGOAUX:=NULL;
  END IF;

  UPDATE RECIBOS SET
      NIF=xNIF,NOMBRE=xNOMBRE,FCALLE=xCALLE,FNUMERO=xNUMERO,FBLOQUE=xBLOQUE,
      FESCALERA=xESCALERA,FPLANTA=xPLANTA,FPISO=xPISO,FLETRA=xLETRA,FCODPOST=xCODPOSTAL,
      FPOBLACION=xPOBLACION,DOMICILIADO=xDOMICILIADO,DNI_TITULAR=xNIFT,NOMBRE_TITULAR=xNOMBRET,
      ENTIDAD=xENTIDAD,SUCURSAL=xSUCURSAL,DC=xDC,CUENTA=xCUENTA,ESTADO_BANCO=xESTADO,
      DESDE=xDESDEAUX,HASTA=xHASTAAUX,NOTIFICADO=xNOTIFICADO,F_NOTIFICACION=xFECHANOTIFAUX,
      VOL_EJE=xVOLEJE,F_CARGO=xFECHACARGOAUX,CARGO=xCARGO,CINICIAL=xCINICIAL,
	PRINCIPAL=xPRINCIPAL,RECARG_O_E=xRECARGO_O_E,RECARGO=xRECARGO,COSTAS=xCOSTAS,
      DEMORA=xDEMORA,ENTREGAS=xENTREGAS,REFERENCIA=xREFERENCIA,DIGITO_CONTROL=xDC60,
      TRIBUTO=xTRIBUTO,EJERCICIO=xEJERCICIO,REMESA=xREMESA,IMPORTE=xIMPORTE,EMISOR=xEMISOR,
      TCALLE=xCALLET,TNUMERO=xNUMEROT,TBLOQUE=xBLOQUET,TESCALERA=xESCALERAT,TPLANTA=xPLANTAT,
      TPISO=xPISOT,TLETRA=xLETRAT,TCODPOST=xCODPOSTALT,TPOBLACION=xPOBLACIONT,CONCEPTO01=xVAR1,
      CONCEPTO02=xVAR2,CONCEPTO03=xVAR3,CONCEPTO04=xVAR4,CONCEPTO05=xVAR5,CONCEPTO06=xVAR6,
      CONCEPTO07=xVAR7,CONCEPTO08=xVAR8,CONCEPTO09=xVAR9,CONCEPTO10=xVAR10,CONCEPTO11=xVAR11
  WHERE ID=XID;

END;
/


/********************************************************************/
COMMIT;
/********************************************************************/
